spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: db/changelog/changelog-master.xml
  jackson:
    default-property-inclusion: non_null